routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    $jurusans = \App\Models\Jurusan::all();
    $berita = \App\Models\Berita::whereStatus('active')->orderBy('created_at','DESC')->limit(3)->get();
    $prfile = \App\Models\Profile::first();
    $kepsek = \App\Models\Kepsek::first();
    $carousel = [];
    $i = 0;

    foreach ($berita as $a){
        $carousel[$i] = $a;
        $i++;
    }
    $carousel1 = $carousel[0];
    $carousel2 = $carousel[1];
    $carousel3 = $carousel[2];

//    dd($carousel);

    view()->share([
        'jurusans' => $jurusans,
        'berita' => $berita,
        'profile' => $prfile,
        'kepsek' => $kepsek,
        'carousel1' => $carousel1,
        'carousel2' => $carousel2,
        'carousel3' => $carousel3
    ]);
    return view('landing.content.index');
});

Route::group(['prefix'=>'admin','as'=>'admin.','middleware'=>['auth']],function (){

    Route::group(['as'=>'auth.'],function (){
        Route::get('dashboard',[\App\Http\Controllers\Admin\DashboardController::class,'index'])->name('dashboard');

        Route::resource('jurusan', \App\Http\Controllers\Admin\JurusanController::class);
        Route::get('jurusan/destroy/{id}',[\App\Http\Controllers\Admin\JurusanController::class,'destroy'])->name('jurusanDestroy');
        Route::get('jurusan/detail/{id}',[\App\Http\Controllers\Admin\JurusanController::class,'detailForm'])->name('jurusanDetail');
        Route::post('jurusan/detail/{id}',[\App\Http\Controllers\Admin\JurusanController::class,'detailFormAction'])->name('jurusanDetailAction');
//        Route::pu('jurusan/detail/{id}',[\App\Http\Controllers\Admin\JurusanController::class,'detailFormActionEdit'])->name('jurusanDetailActionEdit');

        Route::resource('VisiMisi', \App\Http\Controllers\Admin\VisiMisiController::class);
        Route::get('VisiMisi/destroy/{id}',[\App\Http\Controllers\Admin\VisiMisiController::class,'destroy'])->name('VisiMisiDestroy');

        Route::resource('Struktur', \App\Http\Controllers\Admin\StrukturController::class);
        Route::get('Struktur/destroy/{id}',[\App\Http\Controllers\Admin\StrukturController::class,'destroy'])->name('strukturDestroy');

        Route::resource('karyawan', \App\Http\Controllers\Admin\KaryawanController::class);
        Route::get('karyawan/destroy/{id}',[\App\Http\Controllers\Admin\KaryawanController::class,'destroy'])->name('karyawanDestroy');

        Route::resource('berita', \App\Http\Controllers\Admin\BeritaController::class);
        Route::get('berita/destroy/{id}',[\App\Http\Controllers\Admin\BeritaController::class,'destroy'])->name('beritaDestroy');

        Route::resource('kategori', \App\Http\Controllers\Admin\KategoriController::class);
        Route::get('kategori/destroy/{id}',[\App\Http\Controllers\Admin\KategoriController::class,'destroy'])->name('kategoriDestroy');

        Route::resource('profile', \App\Http\Controllers\Admin\ProfileController::class);
        Route::get('profile/destroy/{id}',[\App\Http\Controllers\Admin\ProfileController::class,'destroy'])->name('kategoriDestroy');

        Route::resource('kepsek', \App\Http\Controllers\Admin\KepsekController::class);
        Route::get('kepsek/destroy/{id}',[\App\Http\Controllers\Admin\KepsekController::class,'destroy'])->name('kepsekDestroy');

        Route::resource('sarana', \App\Http\Controllers\Admin\SaranaController::class);
        Route::get('sarana/destroy/{id}',[\App\Http\Controllers\Admin\SaranaController::class,'destroy'])->name('saranaDestroy');

        Route::resource('galery', \App\Http\Controllers\Admin\GaleryController::class);
        Route::get('galery/destroy/{id}',[\App\Http\Controllers\Admin\GaleryController::class,'destroy'])->name('galeryDestroy');

        Route::resource('pengumuman', \App\Http\Controllers\Admin\PengumumanController::class);
        Route::get('pengumuman/destroy/{id}',[\App\Http\Controllers\Admin\PengumumanController::class,'destroy'])->name('pengumumanDestroy');

    });
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::get('/visimisi', [App\Http\Controllers\Landing\VisiMisiController::class, 'index'])->name('visimisi');
Route::get('/struktur', [App\Http\Controllers\Landing\StrukturController::class, 'index'])->name('struktur');
Route::get('/pengumuman', [App\Http\Controllers\Landing\StrukturController::class, 'pengumuman'])->name('pengumuman');
Route::get('/karyawan', [App\Http\Controllers\Landing\KaryawanController::class, 'index'])->name('karyawan');
Route::get('/saranaPrasarana', [App\Http\Controllers\Landing\SaranaController::class, 'index'])->name('sarana');
Route::get('/galery', [App\Http\Controllers\Landing\GaleryController::class, 'index'])->name('galery');
Route::get('/detail/{slug}',[\App\Http\Controllers\HomeController::class,'detail'])->name('detail');
Route::get('/detailJurusan/{id}',[\App\Http\Controllers\HomeController::class,'detailJurusan'])->name('detailJurusan');
Route::get('more-new',[\App\Http\Controllers\HomeController::class,'moreNew'])->name('moreNew');
Route::get('/kontak',[\App\Http\Controllers\HomeController::class,'kontak'])->name('kontak');
Route::post('search',[\App\Http\Controllers\HomeController::class,'searchAction'])->name('searchAction');

app/Models/Profile.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Profile extends Model
{
    use HasFactory;
}

app/Http/Controllers/Admin/ProfileController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Profile;
use App\Models\VisiMisi;
use Illuminate\Http\Request;

class ProfileController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = Profile::first();

        view()->share([
            'data' => $data
        ]);
        return view('admin.content.profile.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data = Profile::find($id);
        view()->share([
            'data' => $data
        ]);
        return view('admin.content.profile.form');
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $data = Profile::find($id);

        $data->dsc = $request->dsc;
        $data->youtube = $request->youtube;

        $data->save();
        return redirect()->route('admin.auth.profile.index')->withSuccess('Succcess Edit data');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/content/profile/form.blade.php
@extends('admin.app')

@section('content')


<div class="main-content">
        <section class="section">
            <div class="section-header">
                <h1>Form Jurusan</h1>
            </div>
            <div class="section-body">
                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <div class="card-body">
                                <form action="{{($data!=null) ? route('admin.auth.profile.update',$data->id) : route('admin.auth.profile.index')}}" method="post" enctype="multipart/form-data">
                                    @csrf
                                    @if($data!=null)
                                        @method('put')
                                    @endif


                                    <div class="form-group row mb-4">
                                        <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">dsc</label>
                                        <div class="col-sm-12 col-md-7">
                                            <input type="text" name="dsc" id="dsc" class="form-control @error('dsc') is-invalid @enderror" value="{{($data!=null) ? $data->dsc : ''}}">
                                            @error('dsc')
                                            <div class="alert alert-danger">{{ $message }}</div>
                                            @enderror
                                        </div>
                                    </div>

                                    <div class="form-group row mb-4">
                                        <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Youtube</label>
                                        <div class="col-sm-12 col-md-7">
                                            <input type="text" name="youtube" id="youtube" class="form-control @error('youtube') is-invalid @enderror" value="{{($data!=null) ? $data->youtube : ''}}">
                                            @error('youtube')
                                            <div class="alert alert-danger">{{ $message }}</div>
                                            @enderror
                                        </div>
                                    </div>

                                    <div class="form-group row mb-4">
                                        <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3"></label>
                                        <div class="col-sm-12 col-md-7">
                                            <button class="btn btn-primary">save</button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>

    <script>
        $(document).ready(function() {
            $('#summernote').summernote();
        });

        $(document).ready(function() {
            $('#summernotea').summernote();
        });

    </script>
@endsection

resources/views/admin/content/profile/index.blade.php
@extends('admin.app')

@section('content')


    <!-- Main Content -->
    <div class="main-content">
        <section class="section">
            <div class="section-header">
                <h1>Master</h1>
            </div>

            <div class="section-body">
                <h2 class="section-title">Jurusan</h2>
                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <div class="card-body">
{{--                                @if($data == null)--}}
{{--                                    <a href="{{route('admin.auth.VisiMisi.create')}}" class="btn btn-success text-white">create</a>--}}
{{--                                @endif--}}
                                <br><br>
                                @include('admin.components.partials.message')
                                <div class="table-responsive">
                                    <table class=" table table-striped" id="item">
                                        <thead>
                                        <tr>
                                            <th>dsc</th>
                                            <th>youtube</th>
                                            <th>Action</th>
                                        </tr>
                                        </thead>

                                        <tbody>
                                        <tr>
                                            <td>{{$data->dsc}}</td>
                                            <td>{{$data->youtube}}</td>
                                            <td>
                                                <a href="{{route('admin.auth.profile.edit',$data->id)}}" class="btn btn-primary text-white">Edit</a>
{{--                                                <a href="{{route('admin.auth.VisiMisiDestroy',$data->id)}}" onclick="return confirm(`Are you sure?`)" class="btn btn-danger text-white">Delete</a>--}}
                                            </td>
                                        </tr>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
    @push('script')
        <script type="text/javascript">
            $(document).ready(function(){
                $('#item').DataTable({
                });
            });
        </script>

    @endpush
@endsection