routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    $jurusans = \App\Models\Jurusan::all();
    $berita = \App\Models\Berita::whereStatus('active')->orderBy('created_at','DESC')->limit(3)->get();
    $prfile = \App\Models\Profile::first();
    $kepsek = \App\Models\Kepsek::first();
    $carousel = [];
    $i = 0;

    foreach ($berita as $a){
        $carousel[$i] = $a;
        $i++;
    }
    $carousel1 = $carousel[0];
    $carousel2 = $carousel[1];
    $carousel3 = $carousel[2];

//    dd($carousel);

    view()->share([
        'jurusans' => $jurusans,
        'berita' => $berita,
        'profile' => $prfile,
        'kepsek' => $kepsek,
        'carousel1' => $carousel1,
        'carousel2' => $carousel2,
        'carousel3' => $carousel3
    ]);
    return view('landing.content.index');
});

Route::group(['prefix'=>'admin','as'=>'admin.','middleware'=>['auth']],function (){

    Route::group(['as'=>'auth.'],function (){
        Route::get('dashboard',[\App\Http\Controllers\Admin\DashboardController::class,'index'])->name('dashboard');

        Route::resource('jurusan', \App\Http\Controllers\Admin\JurusanController::class);
        Route::get('jurusan/destroy/{id}',[\App\Http\Controllers\Admin\JurusanController::class,'destroy'])->name('jurusanDestroy');
        Route::get('jurusan/detail/{id}',[\App\Http\Controllers\Admin\JurusanController::class,'detailForm'])->name('jurusanDetail');
        Route::post('jurusan/detail/{id}',[\App\Http\Controllers\Admin\JurusanController::class,'detailFormAction'])->name('jurusanDetailAction');
//        Route::pu('jurusan/detail/{id}',[\App\Http\Controllers\Admin\JurusanController::class,'detailFormActionEdit'])->name('jurusanDetailActionEdit');

        Route::resource('VisiMisi', \App\Http\Controllers\Admin\VisiMisiController::class);
        Route::get('VisiMisi/destroy/{id}',[\App\Http\Controllers\Admin\VisiMisiController::class,'destroy'])->name('VisiMisiDestroy');

        Route::resource('Struktur', \App\Http\Controllers\Admin\StrukturController::class);
        Route::get('Struktur/destroy/{id}',[\App\Http\Controllers\Admin\StrukturController::class,'destroy'])->name('strukturDestroy');

        Route::resource('karyawan', \App\Http\Controllers\Admin\KaryawanController::class);
        Route::get('karyawan/destroy/{id}',[\App\Http\Controllers\Admin\KaryawanController::class,'destroy'])->name('karyawanDestroy');

        Route::resource('berita', \App\Http\Controllers\Admin\BeritaController::class);
        Route::get('berita/destroy/{id}',[\App\Http\Controllers\Admin\BeritaController::class,'destroy'])->name('beritaDestroy');

        Route::resource('kategori', \App\Http\Controllers\Admin\KategoriController::class);
        Route::get('kategori/destroy/{id}',[\App\Http\Controllers\Admin\KategoriController::class,'destroy'])->name('kategoriDestroy');

        Route::resource('profile', \App\Http\Controllers\Admin\ProfileController::class);
        Route::get('profile/destroy/{id}',[\App\Http\Controllers\Admin\ProfileController::class,'destroy'])->name('kategoriDestroy');

        Route::resource('kepsek', \App\Http\Controllers\Admin\KepsekController::class);
        Route::get('kepsek/destroy/{id}',[\App\Http\Controllers\Admin\KepsekController::class,'destroy'])->name('kepsekDestroy');

        Route::resource('sarana', \App\Http\Controllers\Admin\SaranaController::class);
        Route::get('sarana/destroy/{id}',[\App\Http\Controllers\Admin\SaranaController::class,'destroy'])->name('saranaDestroy');

        Route::resource('galery', \App\Http\Controllers\Admin\GaleryController::class);
        Route::get('galery/destroy/{id}',[\App\Http\Controllers\Admin\GaleryController::class,'destroy'])->name('galeryDestroy');

        Route::resource('pengumuman', \App\Http\Controllers\Admin\PengumumanController::class);
        Route::get('pengumuman/destroy/{id}',[\App\Http\Controllers\Admin\PengumumanController::class,'destroy'])->name('pengumumanDestroy');

    });
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::get('/visimisi', [App\Http\Controllers\Landing\VisiMisiController::class, 'index'])->name('visimisi');
Route::get('/struktur', [App\Http\Controllers\Landing\StrukturController::class, 'index'])->name('struktur');
Route::get('/pengumuman', [App\Http\Controllers\Landing\StrukturController::class, 'pengumuman'])->name('pengumuman');
Route::get('/karyawan', [App\Http\Controllers\Landing\KaryawanController::class, 'index'])->name('karyawan');
Route::get('/saranaPrasarana', [App\Http\Controllers\Landing\SaranaController::class, 'index'])->name('sarana');
Route::get('/galery', [App\Http\Controllers\Landing\GaleryController::class, 'index'])->name('galery');
Route::get('/detail/{slug}',[\App\Http\Controllers\HomeController::class,'detail'])->name('detail');
Route::get('/detailJurusan/{id}',[\App\Http\Controllers\HomeController::class,'detailJurusan'])->name('detailJurusan');
Route::get('more-new',[\App\Http\Controllers\HomeController::class,'moreNew'])->name('moreNew');
Route::get('/kontak',[\App\Http\Controllers\HomeController::class,'kontak'])->name('kontak');
Route::post('search',[\App\Http\Controllers\HomeController::class,'searchAction'])->name('searchAction');

app/Models/Karyawan.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Karyawan extends Model
{
    use HasFactory;
}

app/Http/Controllers/Admin/KaryawanController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Jurusan;
use App\Models\Karyawan;
use Illuminate\Http\Request;

class KaryawanController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = Karyawan::all();

        view()->share([
            'data' => $data
        ]);
        return view('admin.content.karyawan.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data = null;
        view()->share([
            'data' => $data
        ]);
        return view('admin.content.karyawan.form');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = new Karyawan();

        $data->name = $request->name;

        if ($request->file('image')){
            $file = $request->file('image');
            $name = rand(999999999,1);
            $extension = $file->getClientOriginalExtension();
            $newName = $name.'.'.$extension;
            $imgDB = 'uploads/'.$newName;

            $request->image->move(public_path('uploads/'), $newName);
            $data->img = $imgDB;
        }else{
            $data->img = $data->img ;
        }

        $data->mapel = $request->mapel;
        $data->type = $request->type;

        $data->save();
        return redirect()->route('admin.auth.karyawan.index')->withSuccess('Succcess create data');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data = Karyawan::find($id);
        view()->share([
            'data' => $data
        ]);
        return view('admin.content.karyawan.form');
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $data = Karyawan::find($id);

        $data->name = $request->name;

        if ($request->file('image')){
            $file = $request->file('image');
            $name = rand(999999999,1);
            $extension = $file->getClientOriginalExtension();
            $newName = $name.'.'.$extension;
            $imgDB = 'uploads/'.$newName;

            $request->image->move(public_path('uploads/'), $newName);
            $data->img = $imgDB;
        }else{
            $data->img = $data->img ;
        }

        $data->mapel = $request->mapel;
        $data->type = $request->type;

        $data->save();
        return redirect()->route('admin.auth.karyawan.index')->withSuccess('Succcess create data');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $data = Karyawan::find($id);

//        dd($data);
        $data->delete();

        return redirect()->route('admin.auth.karyawan.index')->withSuccess('Succcess Delete data');
    }
}

app/Http/Controllers/Landing/KaryawanController.php
<?php

namespace App\Http\Controllers\Landing;

use App\Http\Controllers\Controller;
use App\Models\Karyawan;
use App\Models\Struktur;
use Illuminate\Http\Request;

class KaryawanController extends Controller
{
    public function index(){
//        dd('dwqdqw');
        $data = Karyawan::all();
        $jurusans = \App\Models\Jurusan::all();

        view()->share([
            'data' => $data,
            'jurusans' => $jurusans
        ]);
        return view('landing.content.karyawan');
    }
}

resources/views/admin/content/karyawan/form.blade.php
@extends('admin.app')

@section('content')


<div class="main-content">
        <section class="section">
            <div class="section-header">
                <h1>Form karyawan</h1>
            </div>
            <div class="section-body">
                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <div class="card-body">
                                <form action="{{($data!=null) ? route('admin.auth.karyawan.update',$data->id) : route('admin.auth.karyawan.index')}}" method="post" enctype="multipart/form-data">
                                    @csrf
                                    @if($data!=null)
                                        @method('put')
                                    @endif
                                    <div class="form-group row mb-4">
                                        <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Nama</label>
                                        <div class="col-sm-12 col-md-7">
                                            <input type="text" name="name" id="name" class="form-control @error('name') is-invalid @enderror" value="{{($data!=null) ? $data->name : ''}}">
                                            @error('name')
                                            <div class="alert alert-danger">{{ $message }}</div>
                                            @enderror
                                        </div>
                                    </div>
                                    <div class="form-group row mb-4">
                                        <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Image</label>
                                        <div class="col-sm-12 col-md-7">
                                            <input type="file" name="image" id="image">
                                        </div>
                                    </div>
                                    <div class="form-group row mb-4">
                                        <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Mapel</label>
                                        <div class="col-sm-12 col-md-7">
                                            <input type="text" name="mapel" id="mapel" class="form-control @error('mapel') is-invalid @enderror" value="{{($data!=null) ? $data->mapel : ''}}">
                                            @error('mapel')
                                            <div class="alert alert-danger">{{ $message }}</div>
                                            @enderror
                                        </div>
                                    </div>

                                    <div class="form-group row mb-4">
                                        <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Mapel</label>
                                        <div class="col-sm-12 col-md-7">
                                            <select class="form-control" id="exampleFormControlSelect1" name="type">
                                                @if($data!=null)
                                                    @if($data->type == '0')
                                                        <option value="0" selected>Tenaga Kependidikan</option>
                                                    @else
                                                        <option value="1" selected>Guru</option>
                                                    @endif
                                                @endif
                                                <option value="0">Tenaga Kependidikan</option>
                                                <option value="1">Guru</option>
                                            </select>
                                        </div>
                                    </div>

                                    <div class="form-group row mb-4">
                                        <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3"></label>
                                        <div class="col-sm-12 col-md-7">
                                            <button class="btn btn-primary">save</button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
    <script>
        $(document).ready(function() {
            $('#summernote').summernote();
        });

    </script>
@endsection

resources/views/admin/content/karyawan/index.blade.php
@extends('admin.app')

@section('content')


    <!-- Main Content -->
    <div class="main-content">
        <section class="section">
            <div class="section-header">
                <h1>Master</h1>
            </div>

            <div class="section-body">
                <h2 class="section-title">karyawan</h2>
                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <div class="card-body">
{{--                                @if($data == null)--}}
                                    <a href="{{route('admin.auth.karyawan.create')}}" class="btn btn-success text-white">create</a>
{{--                                @endif--}}
                                <br><br>
                                @include('admin.components.partials.message')
                                <div class="table-responsive">
                                    <table class=" table table-striped" id="item">
                                        <thead>
                                        <tr>
                                            <th>Nama</th>
                                            <th>Image</th>
                                            <th>Mapel</th>
                                            <th>Type</th>
                                            <th>Action</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        @foreach($data as $karyawan)
                                            <tr>
                                                <td>{{$karyawan->name}}</td>
                                                <td><img src="{{asset($karyawan->img)}}" width="50"></td>
                                                <td>{{$karyawan->mapel}}</td>
                                                <td>{{($karyawan->type == 0) ? 'Tenaga Pendidik' : 'Guru' }}</td>
                                                <td>
                                                    <a href="{{route('admin.auth.karyawan.edit',$karyawan->id)}}" class="btn btn-primary text-white">Edit</a>
                                                    <a href="{{route('admin.auth.karyawanDestroy',$karyawan->id)}}" onclick="return confirm(`Are you sure?`)" class="btn btn-danger text-white">Delete</a>
                                                </td>
                                            </tr>

                                        @endforeach
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
    @push('script')
        <script type="text/javascript">
            $(document).ready(function(){
                $('#item').DataTable({
                });
            });
        </script>

    @endpush
@endsection